Update test specs
[spec] Revamp test
[spec] Fix "[Error: Cannot find module '../www']"
[spec] Add missing 'typeof' to the assetions.
[git] Ignore the node_modules/ directory.
[spec] fix failing tests